import { expect, test } from "@playwright/test";
import fs from "node:fs/promises";

test("Chinese default and English switch preserve geometry, notes and legacy review import", async ({ page }) => {
  const errors: string[] = []; page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/");
  await expect(page.locator("html")).toHaveAttribute("lang", "zh-CN");
  await page.getByRole("button", { name: "试用合成示例" }).click();
  const canvas = await page.locator("canvas").elementHandle();
  await page.locator(".layer-row input").first().uncheck();
  await page.getByRole("button", { name: "审阅记录", exact: true }).click();
  await page.getByLabel("新增记录").fill("尚未打开 — user note stays unchanged");
  await page.getByRole("button", { name: "加入记录", exact: true }).click();
  await page.getByRole("button", { name: "切换为英文", exact: true }).click();
  await expect(page.locator("html")).toHaveAttribute("lang", "en");
  await expect(page).toHaveTitle("GDS-3D-VIEWER · 3D Layout Preview");
  await expect(page.locator(".note-item")).toContainText("尚未打开 — user note stays unchanged");
  await expect(page.locator(".main-foot")).toContainText("AIALRA_DEMO");
  expect(await canvas!.evaluate((element) => element.isConnected)).toBe(true);
  await expect(page.getByRole("heading", { name: "Geometry statistics" })).toBeVisible();
  await expect(page.getByText("Layer heights follow display order for inspection and do not represent process thickness", { exact: true })).toHaveCount(1);
  await page.getByRole("button", { name: "Layers", exact: true }).click();
  await expect(page.locator(".layer-row input").first()).not.toBeChecked();
  await page.getByRole("button", { name: "Help and privacy" }).click();
  await expect(page.getByRole("dialog")).toContainText("Files and sessions");
  await page.getByRole("button", { name: "Back to workspace" }).click();
  const download = page.waitForEvent("download");
  await page.getByRole("button", { name: "Export review" }).click();
  const review = JSON.parse(await fs.readFile((await (await download).path())!, "utf8"));
  expect(review.format).toBe("gds-3d-viewer-review");
  review.format = "icviewer-review";
  await page.getByTestId("review-file-input").setInputFiles({ name: "old-review.json", mimeType: "application/json", buffer: Buffer.from(JSON.stringify(review)) });
  await expect(page.getByRole("status")).toContainText("Review restored to this session");
  await page.reload();
  await expect(page.locator("html")).toHaveAttribute("lang", "en");
  await expect(page.getByRole("button", { name: "Open file", exact: true }).first()).toBeVisible();
  await page.getByRole("button", { name: "Switch to Chinese" }).click();
  await expect(page.locator("html")).toHaveAttribute("lang", "zh-CN");
  expect(errors).toEqual([]);
});

test("narrow AI controls do not overlap and Markdown is formatted without active HTML or resources", async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem("gds-3d-viewer.preferences.v1", JSON.stringify({ widths: [256, 220], theme: "dark" })));
  await page.goto("/");
  await page.getByRole("button", { name: "试用合成示例" }).click();
  await expect(page.locator(".viewer-host canvas")).toBeVisible();
  await page.getByRole("button", { name: "切换为英文" }).click();
  const panel = page.getByRole("region", { name: "AI explanation", exact: true });
  await panel.getByText("Configure this session", { exact: true }).click();
  const endpoint = "https://models.example.invalid/v1/chat/completions";
  await panel.getByLabel("Model endpoint", { exact: true }).fill(endpoint);
  await panel.getByLabel("Session API key", { exact: true }).fill("synthetic-markdown-key");
  await panel.getByLabel("Confirm sending the selected summary").check();
  let finish!: () => void;
  const ready = new Promise<void>((resolve) => { finish = resolve; });
  const external: string[] = [];
  page.on("request", (request) => { if (request.url().includes("unsafe.example.invalid")) external.push(request.url()); });
  let body: any;
  await page.route(endpoint, async (route) => {
    body = route.request().postDataJSON();
    await ready;
    await route.fulfill({ contentType: "application/json", body: JSON.stringify({ choices: [{ message: { content: "## Known facts\n\n**Measured geometry** with `PATH`\n\n1. First item\n2. Second item\n\n- Layer\n  - Nested fact\n\n| Attribute | Value |\n| --- | --- |\n| Cell | AIALRA_DEMO |\n\n```text\n<not-active>\n```\n\n> Check electrical connectivity separately\n\n<script>window.modelExecuted=true</script>\n<img src=\"https://unsafe.example.invalid/html.png\" onerror=\"alert(1)\">\n\n![remote](https://unsafe.example.invalid/image.png)\n\n[external](https://unsafe.example.invalid/link)\n\n[unsafe](javascript:alert(1))" } }] }) });
  });
  await panel.getByRole("button", { name: "Generate explanation", exact: true }).click();
  const generate = panel.getByRole("button", { name: "Generating…", exact: true });
  const cancel = panel.getByRole("button", { name: "Cancel explanation", exact: true });
  await expect(cancel).toBeVisible();
  const first = (await generate.boundingBox())!, second = (await cancel.boundingBox())!;
  expect(first.x + first.width <= second.x || first.y + first.height <= second.y || second.x + second.width <= first.x || second.y + second.height <= first.y).toBe(true);
  finish();
  const result = panel.getByLabel("Explanation result", { exact: true });
  await expect(result.getByRole("heading", { name: "Known facts" })).toBeVisible();
  await expect(result.locator("strong")).toHaveText("Measured geometry");
  await expect(result.locator("ol > li")).toHaveCount(2);
  await expect(result.locator("ul ul li")).toHaveText("Nested fact");
  await expect(result.locator("table td").last()).toHaveText("AIALRA_DEMO");
  await expect(result.locator("pre code")).toContainText("<not-active>");
  await expect(result.locator("script, img, iframe, a, [onerror]")).toHaveCount(0);
  expect(external).toEqual([]);
  expect(await page.evaluate(() => (window as any).modelExecuted)).toBeUndefined();
  expect(body.messages[0].content).toContain("Write Markdown in English");
  expect(JSON.parse(body.messages[1].content).language).toBe("en");
  await panel.getByRole("button", { name: "Clear key", exact: true }).click();
  await expect(panel.getByLabel("Session API key", { exact: true })).toHaveValue("");
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole("button", { name: "Switch to Chinese" }).click();
  await expect(page.locator(".topbar")).toBeVisible();
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth);
  expect(overflow).toBe(false);
});
